spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/news_forum?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum

    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
